apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: default-dsc

resources:
  - rbac.yaml
  - inferenceservice-config.yaml
  - missing-crds.yaml
  - kserve-model-serving.yaml

commonLabels:
  app.kubernetes.io/name: llmops-models
  validated-patterns.io/pattern: llmops-platform


